apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: portal-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/karimbzu/centurion.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: portal-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/centurion/portal:latest
